- name: variables
  hosts: local
  connection: local
  vars:
    COURSE: "devops with aws"
    DURATION: "120 hours"
    TRAINER: "shiva kumar"
  tasks:
  - name: print using variables
      COURSE: "Ansible"
    ansible.builtin.debug:
      msg: "couse is {{COURSE}} and the duration is {{DURATION}} with {{TRAINER}}"

  - name: print using variables
    ansible.builtin.debug:
      msg: "couse is {{COURSE}} and the duration is {{DURATION}} with {{TRAINER}}"
