- name: variables
  hosts: local
  connection: local
  vars_file:
  - vars_file.yaml
  tasks:
  - name: print using variables
    vars:
      COURSE: "Ansible"
    ansible.builtin.debug:
      msg: "couse is {{COURSE}} and the duration is {{DURATION}} with {{TRAINER}}"

  - name: print using variables
    ansible.builtin.debug:
      msg: "couse is {{COURSE}} and the duration is {{DURATION}} with {{TRAINER}}"
